---
# tasks file for informix-jdbc

- name: check whether the vendor is HCL
  fail:
    msg: "IBM does not package JDBC separately, this only works for an HCL distribution"
  when: vendor != "hcl"

- name: check if this version is already installed
  stat:
    path: "{{ jdbc_install_path }}/.install_complete"
  register: st
  ignore_errors: true

- name: set already installed flag if necessary
  set_fact:
    jdbc_version_previously_installed: true
  when: st.stat.exists is defined and st.stat.exists

- name: check if force install flag is set
  set_fact:
    jdbc_version_previously_installed: false
  when: force_jdbc_install

- name: set the install media file name if HCL
  set_fact:
    jdbc_install_media_name: "hcl.jdbc.{{ jdbc_version }}.ALL.tar.gz"
  when: vendor == "hcl" and not jdbc_version_previously_installed

- name: set selinux permissive
  selinux:
    policy: targeted
    state: permissive
  when: ansible_facts['os_family'] == "RedHat" and not jdbc_version_previously_installed

- name: install python and Java on Debian platforms
  apt:
    name:
    - python2.7
    - openjdk-8-jdk
  register: task_result
  until: task_result is success
  retries: 150
  delay: 2
  when: ansible_facts['os_family'] == "Debian" and not jdbc_version_previously_installed

- name: install Java on SuSE platforms
  zypper:
    name:
    - java-1_8_0-openjdk
  register: task_result
  until: task_result is success
  retries: 150
  delay: 2
  when: ansible_facts['os_family'] == "Suse" and not jdbc_version_previously_installed

- name: create informix group
  group:
    name: informix
    state: present
    system: false
  when: not jdbc_version_previously_installed

- name: create informix user
  user:
    home: /opt/informix
    group: informix
    name: informix
    shell: /bin/bash
    state: present
    system: false
  when: not jdbc_version_previously_installed

- name: create target install directory
  file:
    group: informix
    mode: 0775
    owner: informix
    path: "{{ jdbc_install_path }}"
    state: directory
  when: not jdbc_version_previously_installed

- name: create temp install directory
  file:
    group: informix
    mode: 0775
    owner: informix
    path: "{{ jdbc_tmp_path }}"
    state: directory
  when: not jdbc_version_previously_installed

- name: upload / download and extract JDBC installer
  unarchive:
    dest: "{{ jdbc_tmp_path }}"
    src: "{{ source_location_of_jdbc_media }}/{{ jdbc_install_media_name }}"
  when: not jdbc_version_previously_installed

- name: run installer
  become: true
  command: java -jar setup.jar -i silent -DLICENSE=accepted -DUSER_INSTALL_DIR="{{ jdbc_install_path }}"
  args:
    chdir: "{{ jdbc_tmp_path }}"
  when: not jdbc_version_previously_installed

- name: validate install
  stat:
    path: "{{ jdbc_install_path }}/lib/ifxjdbc.jar"
  register: val
  ignore_errors: true

- name: abort install failed
  fail:
    msg: "Install failed - ifxjdbc.jar does not exist or is zero bytes"
  when: not val.stat.exists or val.stat.size == 0

- name: make this the default version by linking "informixdir" to it
  file:
    group: informix
    mode: 0775
    owner: informix
    src: "{{ jdbc_install_path }}"
    dest: "{{ jdbc_base_path }}/informixdir"
    state: link
  when: not jdbc_version_previously_installed

- name: clean up
  file:
    group: informix
    mode: 0775
    owner: informix
    path: "{{ jdbc_tmp_path }}"
    state: absent
  when: not jdbc_version_previously_installed

- name: mark installation as complete
  file:
    group: informix
    mode: 0400
    owner: informix
    path: "{{ jdbc_install_path }}/.install_complete"
    state: touch
  when: not jdbc_version_previously_installed
